#!/bin/bash

#
# bootstrap.sh version 0.1.0
# https://github.com/AttainIT-Technologies/vm-ubuntu-osint
#

################################
# SCRIPT DEVELOPMENT IN PROGRESS
################################

# UPDATE UBUNTU
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove -y && sudo apt-get autoclean -y

# INSTALL PACKAGES
sudo apt install curl -y
sudo apt install jq -y

# BASHRC UPDATES
echo '#####################' >> ~/.bashrc
echo '# OSINT UPDATES BELOW' >> ~/.bashrc
echo 'OSINT_BIN=~/bin; export OSINT_BIN' >> ~/.bashrc
echo 'PATH=$OSINT_BIN:$PATH' >> ~/.bashrc
echo '# OSINT UPDATES ABOVE' >> ~/.bashrc
echo '#####################' >> ~/.bashrc
