#!/bin/bash

#
# bootstrap.sh version 0.1.0
# https://github.com/AttainIT-Technologies/vm-ubuntu-osint
#

################################
# SCRIPT DEVELOPMENT IN PROGRESS
################################

# UPDATE UBUNTU
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove -y && sudo apt-get autoclean -y

# INSTALL PACKAGES
sudo apt install curl -y
sudo apt install jq -y

# BASHRC UPDATES
echo '#####################' >> ~/.bashrc
echo '# OSINT UPDATES BELOW' >> ~/.bashrc
echo 'OSINT_BIN=~/bin; export OSINT_BIN' >> ~/.bashrc
echo 'PATH=$OSINT_BIN:$PATH' >> ~/.bashrc
echo '# OSINT UPDATES ABOVE' >> ~/.bashrc
echo '#####################' >> ~/.bashrc

# UPDATE UBUNTU GLOBAL SETTINGS
gsettings set org.gnome.system.location enabled false
gsettings set org.gnome.desktop.screensaver lock-enabled false
gsettings set org.gnome.ControlCenter last-panel 'removable-media'
gsettings set org.gnome.desktop.privacy remember-recent-files false
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 3600
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
gsettings set org.gnome.desktop.session idle-delay uint32 0
gsettings set org.gnome.desktop.media-handle autorun-x-content-start-app @as []
gsettings set org.gnome.shell.extensions.dash-to-dock preferred-monitor 0
