#!/bin/bash

#
# bootstrap.sh version 0.1.0
# https://github.com/AttainIT-Technologies/vm-ubuntu-osint
#

################################
# SCRIPT DEVELOPMENT IN PROGRESS
################################

# UPDATE UBUNTU
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove -y && sudo apt-get autoclean -y

# INSTALL PACKAGES
sudo apt install curl -y
sudo apt install jq -y

# BASHRC UPDATES
echo '#####################' >> ~/.bashrc
echo '# OSINT UPDATES BELOW' >> ~/.bashrc
echo 'OSINT_BIN=~/bin; export OSINT_BIN' >> ~/.bashrc
echo 'PATH=$OSINT_BIN:$PATH' >> ~/.bashrc
echo '# OSINT UPDATES ABOVE' >> ~/.bashrc
echo '#####################' >> ~/.bashrc

# UPDATE UBUNTU GLOBAL SETTINGS
gsettings set org.gnome.system.location enabled false
gsettings set org.gnome.desktop.screensaver lock-enabled false
gsettings set org.gnome.ControlCenter last-panel 'diagnostics'
gsettings set org.gnome.desktop.privacy remember-recent-files false
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 3600
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
gsettings set org.gnome.desktop.session idle-delay 0
gsettings set org.gnome.desktop.media-handling autorun-x-content-start-app []
gsettings set org.gnome.shell.extensions.dash-to-dock preferred-monitor 0

sudo apt install openssh-server -y
echo '# OSINT VM SSH UPDATES' | sudo tee -a /etc/ssh/sshd_config
echo 'PermitEmptyPasswords no' | sudo tee -a /etc/ssh/sshd_config
echo 'PermitRootLogin no' | sudo tee -a /etc/ssh/sshd_config
echo 'Protocol 2' | sudo tee -a /etc/ssh/sshd_config
echo 'ClientAliveInterval 300' | sudo tee -a /etc/ssh/sshd_config
echo 'MaxAuthTries 3' | sudo tee -a /etc/ssh/sshd_config
echo 'LoginGraceTime 20' | sudo tee -a /etc/ssh/sshd_config
echo 'ChallengeResponseAuthentication no' | sudo tee -a /etc/ssh/sshd_config
echo 'KerberosAuthentication no' | sudo tee -a /etc/ssh/sshd_config
echo 'GSSAPIAuthentication no' | sudo tee -a /etc/ssh/sshd_config
echo 'X11Forwarding no' | sudo tee -a /etc/ssh/sshd_config
echo 'PermitUserEnvironment no' | sudo tee -a /etc/ssh/sshd_config
echo 'AllowAgentForwarding no' | sudo tee -a /etc/ssh/sshd_config
echo 'AllowTcpForwarding no' | sudo tee -a /etc/ssh/sshd_config
echo 'PermitTunnel no' | sudo tee -a /etc/ssh/sshd_config
echo 'PrintLastLog yes' | sudo tee -a /etc/ssh/sshd_config
sudo service sshd reload

sudo apt install vsftpd -y
sudo openssl req -x509 -nodes -days 3650 -newkey rsa:4096 -subj "/C=US/ST=Denial/L=Springfield/O=osint/CN=osint.local" -keyout /etc/ssl/private/vsftpd.pem -out /etc/ssl/private/vsftpd.pem
echo '# OSINT VM FTP UPDATES' | sudo tee -a /etc/vsftpd.conf
echo 'write_enable=YES' | sudo tee -a /etc/vsftpd.conf
sudo sed -i '/rsa_cert_file/s/^/#/' /etc/vsftpd.conf
sudo sed -i '/rsa_private_key_file/s/^/#/' /etc/vsftpd.conf
sudo sed -i '/ssl_enable/s/^/#/' /etc/vsftpd.conf
echo 'rsa_cert_file=/etc/ssl/private/vsftpd.pem' | sudo tee -a /etc/vsftpd.conf
echo 'rsa_private_key_file=/etc/ssl/private/vsftpd.pem' | sudo tee -a /etc/vsftpd.conf
echo 'ssl_enable=YES' | sudo tee -a /etc/vsftpd.conf
sudo systemctl restart vsftpd
