#!/bin/bash

#
# ubuntu-upgrade.sh version 0.1.0
# https://github.com/AttainIT-Technologies/vm-ubuntu-osint
#

# UPDATE UBUNTU
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove -y && sudo apt-get autoclean -y
